size(200,200);
int valor = 100;
println(valor);
valor = valor + 1;
println(valor);
valor = valor + 1;
println(valor);
valor++; // valor = valor + 1;
println(valor);
valor--; // valor = valor - 1;
println(valor);
